### PR TITLE
Add a method for changing the logged field name for the base message

### PR DESCRIPTION
**Pull request by deltamualpha**
This allows for alternative structures for the JSON output that fit in better with other logging frameworks/parsing backends for the structured output.

### CODE REVIEW

**Comment by jacek99** [comment]
Thank you for your PR. Will look at it over the weekend and merge if all OK.

**Comment by deltamualpha** [comment]
Thanks! Let me know if you want me to implement this for the YAML side, too, since the logic there is basically the same.

**Comment by jacek99** [comment]
Sorry for the delay, will try to look at it this week

**Comment by rliddler** [comment]
I would really like something similar to this for the non-json output where you can label the message rather than printing it without any label compared to the rest of the log line eg:

`msg="this is my message" otherField=something otherthing="also something"`

I'll open up a PR when I next get a chance, but this would be handy in the JSON too!

**Comment by deltamualpha** [comment]
I fixed the test and added a YAML implementation.

@rliddler that sounds different enough that it'd be better in a separate PR.

**Comment by deltamualpha** [comment]
@jacek99 any thoughts?

**Comment by jacek99** [comment]
Sorry guys I am actually on vacation abroad for 2 weeks, will only be back next Monday, sorry about the delay, will definitely look into all of these as soon as I get back

**Comment by deltamualpha** [comment]
going to bump this again, @jacek99.

**Comment by jacek99** [comment]
I apologize for all the delays, been going through crazy death march at my current startup, not really in the mood for after work coding. It's calming down, so I hope to finally look at it this weekend

**Comment by deltamualpha** [comment]
bumping again.

**Comment by deltamualpha** [comment]
Figured I'd pop this up here once more before I let it sink beneath the waves forever.

**Comment by jacek99** [comment]
I greatly apologize for neglecting this library for a while, due to work and life commitments.

Getting back into maintaining it more proactively, now that I actually have chance to use it at my job.

Thank you for your patience.

**Comment by deltamualpha** [comment]
Was reminded that I have this PR open. Should I close it?

**Pull request closed without merging**
